# -*- coding: utf-8 -*-
"""Trabajo_fisica

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19m3ottX27z5DCGlA3rp2jWxM2BZNLXVE
"""

import math


class materiales():
  fe = 0
  FD = 0
  def __init__(self, fe, fd):
    self.fe = fe
    self.fd = fd
  def friccion_estatica(self):
    return self.fe
  def friccion_dinamica(self):
    return self.fd

madera = materiales(0.5, 0.3)
acero_sbr_hielo = materiales(0.03, 0.02)
teflon_teflon = materiales(0.04, 0.04)
caucho_cemento = materiales(1, 0.8)
vidrio_vidrio = materiales(0.9, 0.4) 
ski_nieve = materiales(0.1, 0.005)
madera_cuero = materiales(0.5, 0.4)
aluminio_acero = materiales(0.61, 0.47)

def mostrarMateriales():
  print("1. Madera sobre madera: ", "Fe :", madera.friccion_estatica(), " | Fd :", madera.friccion_dinamica())
  
  print("2. Acero sobre hielo: ", "Fe :", acero_sbr_hielo.friccion_estatica(), "| Fd :", acero_sbr_hielo.friccion_dinamica())
  
  print("3. Teflon sobre teflon: ", "Fe :", teflon_teflon.friccion_estatica(), "| Fd :", teflon_teflon.friccion_dinamica())
  
  print("4. Caucho sobre cemento: ", "Fe :", caucho_cemento.friccion_estatica(), "| Fd :", caucho_cemento.friccion_dinamica())
  
  print("5. Vidrio sobre vidrio: ", "Fe :", vidrio_vidrio.friccion_estatica(), "| Fd :", vidrio_vidrio.friccion_dinamica())
  
  print("6. Skiando en nieve: ", "Fe :", ski_nieve.friccion_estatica(), "| Fd :", ski_nieve.friccion_dinamica())
  
  print("7. Madera sobre cuero: ", "Fe :", madera_cuero.friccion_estatica(), "| Fd :", madera_cuero.friccion_dinamica())
  
  print("8. Aluminio sobre acero: ", "Fe :", aluminio_acero.friccion_estatica(), "| Fd :", aluminio_acero.friccion_dinamica())
while True:
  masa=float(input("Ingresa la masa del objeto: "))
  if masa>0: break
  print("Error, no puede ser negativo")
  
fuerza=float(input("Ingresa la fuerza aplicada al objeto (si es un plano inclinado la fuerza se le añadira al peso en X): "))
friccion = input("Hay fricción? Si/No: ")
preg_plan_inclinado = input("Es un plano inclinado? ")

if preg_plan_inclinado.lower()=="si" and friccion.lower()=="si":
  pase=0
  while pase==0:
    angulo = float(input("Cuanta es la inclinacion? Tiene que ser menor que 90 "))
    if angulo < 90 and angulo>0:
      pesy = math.cos(math.radians(angulo))*(masa*9.8)
      pesx = (math.sin(math.radians(angulo))*(masa*9.8)) + fuerza
      
      mostrarMateriales()
      print("9. Si ningun material coincide y quiere hacer fricciones personalizadas")
      material=int(input("Introduzca el material:"))

      if material == 1:
        friccion_e = madera.friccion_estatica()*pesy
        friccion_d = madera.friccion_dinamica()*pesy
      elif material == 2:
        friccion_e = acero_sbr_hielo.friccion_estatica()*pesy
        friccion_d = acero_sbr_hielo.friccion_dinamica()*pesy    
      elif material == 3:
        friccion_e = teflon_teflon.friccion_estatica()*pesy
        friccion_d = teflon_teflon.friccion_dinamica()*pesy    
      elif material == 4:
        friccion_e = caucho_cemento.friccion_estatica()*pesy
        friccion_d = caucho_cemento.friccion_dinamica()*pesy    
      elif material == 5:
        friccion_e = vidrio_vidrio.friccion_estatica()*pesy
        friccion_d = vidrio_vidrio.friccion_dinamica()*pesy    
      elif material == 6:
        friccion_e = ski_nieve.friccion_estatica()*pesy
        friccion_d = ski_nieve.friccion_dinamica()*pesy    
      elif material == 7:
        friccion_e = madera_cuero.friccion_estatica()*pesy
        friccion_d = madera_cuero.friccion_dinamica()*pesy    
      elif material == 8:
        friccion_e = aluminio_acero.friccion_estatica()*pesy
        friccion_d = aluminio_acero.friccion_dinamica()*pesy
      elif material == 9:
        while True:
          custom = materiales(float(input("Introduzca la friccion estatica: ")), float(input("Introduzca la friccion dinamica: ")))
          if custom.friccion_estatica()>1 or custom.friccion_dinamica()>1 or custom.friccion_estatica()<=custom.friccion_dinamica() or custom.friccion_estatica()<0 or custom.friccion_dinamica()<0: 
            print("Error, alguno de los valores es mayor a 1 o la friccion dinamica es mayor a la estatica")
          else: break
        friccion_e = custom.friccion_estatica()*pesy
        friccion_d = custom.friccion_dinamica()*pesy

      aceleracion = (pesx-(friccion_d))/masa
      if aceleracion==0: print("No se mueve :(")
      elif aceleracion>0: print("Se mueve cuesta abajo con una aceleración de:", aceleracion)
      else: print("Se mueve cuesta arriba con una aceleración de:", aceleracion)
      pase=1
    else: 
      print ("NOOO NO POR FAVOR NO NOOO")


elif preg_plan_inclinado.lower() == "si":
  pase=0
  while pase==0:
    angulo = int(input("Cuanta es la inclinacion? Tiene que ser menor que 90 "))
    if angulo < 90 and angulo > 0:
      pesy = math.cos(math.radians(angulo))*(masa*9.8)
      pesx = (math.sin(math.radians(angulo))*(masa*9.8)) + fuerza
      print("El objeto se mueve, su aceleracion es: ", pesx/masa)
      pase=1
    else: print("NOOO NI PDIOS MIO QUE NO ENTENDES")

elif friccion.lower() == "si":
  mostrarMateriales()
  material=int(input("Introduzca el material:"))
  if material == 1 and fuerza<(madera.friccion_estatica()*(masa*9.8)):
    print("El objeto no se mueve")
  elif material == 2 and fuerza<(acero_sbr_hielo.friccion_estatica()*masa*9.8):
    print("El objeto no se mueve")
  elif material == 3 and fuerza<(teflon_teflon.friccion_estatica()*masa*9.8):
    print("El objeto no se mueve")
  elif material == 4 and fuerza<(caucho_cemento.friccion_estatica()*masa*9.8):
    print("El objeto no se mueve")
  elif material == 5 and fuerza<(vidrio_vidrio.friccion_estatica()*masa*9.8):
    print("El objeto no se mueve")
  elif material == 6 and fuerza<(ski_nieve.friccion_estatica()*masa*9.8):
    print("El objeto no se mueve")
  elif material == 7 and fuerza<(madera_cuero.friccion_estatica()*masa*9.8):
    print("El objeto no se mueve")
  elif material == 8 and fuerza<(aluminio_acero.friccion_estatica()*masa*9.8):
    print("El objeto no se mueve")
  else:
    print("El objeto se mueve, su aceleracion es: ", fuerza/masa)
else: 
	print("La aceleracion del objeto es:",fuerza/masa,"m/s^2")